### ISSUE TITLE
Strange log messages related to Lua scripts

### ISSUE THREAD

**Issue by swooboo** [NYRDS/pixel-dungeon-remix#36] opened 2018-01-06 14:47 UTC
These shouldn't be in the player's log probably. I'm running latest app - update yesterday (5/1/18). Happens right after loading and making 1 step.

See here - [Imgur](http://i.imgur.com/ueKUfds.jpg)

![image](https://user-images.githubusercontent.com/900603/34640752-73c43046-f301-11e7-9861-c6235eebe9ba.png)

**Comment by Mikhael-Danilov** [comment] 2018-01-06 17:38
Thanks! Can you please specify exact version ? It is 27.4?
Session where this happens started in this or previous version?

**Comment by swooboo** [comment] 2018-01-06 19:48
It says `v remix.27.4` on the main screen. I see it happening on both a warrior save I started long ago, and a mage one I started today. So both. I use Samsung Galaxy S8+ and Android 7.0. Didn't try to reproduce it on an emulator yet.

**Comment by swooboo** [comment] 2018-01-06 20:06
Can't reproduce it on an emulator yet. Which commit is the one that's 27.4? Is it this one - a69bb2db51b771efb613c81f6947ceece9dd65c8 ? It's commit message is "prepare to 27.4 release".

**Comment by Mikhael-Danilov** [comment] 2018-01-06 20:48
Probably caused by absent lua-side storage in old saves, and likely fixed in
cf903a4d3441817d2d2d37c39452a62871813346

**Comment by Mikhael-Danilov** [comment] 2018-01-06 20:50
No, 27.4 tagged at e333e03213224bd800189cda3ee9562e86354432

**Comment by swooboo** [comment] 2018-01-07 11:23
I didn't understand your explanation. If it's related only to old saves then in my case this is not the problem. All I can tell now is that new games I start also suffer from this, and my current warrior run is unplayable because these things clutter the log.

**Comment by swooboo** [comment] 2018-01-07 14:48
Strange, now It doesn't reproduce on a new save. I do remember starting a new mage run after creating this issue and I saw the messages appear.

Anyway, 2 issues here:

1. These shouldn't appear in the player log.
1. Existing saves still suffer from this.

Both of these might already be fixed, then this issue can be closed.

**Comment by swooboo** [comment] 2018-01-08 15:34
Quick update, I don't face this after updating today. You probably knew and expected this.

**Comment by Mikhael-Danilov** [comment] 2018-01-08 19:53
Sorry I didn't have a chance to answer recently.
I believe this error fixed in 27.4.fix.1

But I will prefer to collect stats for a couple more days before closing it.

About error and it appearance in log:
1) This error caused by improper handling of old saves
2) Not sure if we should remove this kind of errors from users log. ( This errors primary intended for people developing mods, and in most cases logcat is bad option for them ). 
Maybe we should have separate dev-mode log, or something like this...

**Comment by swooboo** [comment] 2018-01-08 20:47
If only modders will see this, I agree it's not a big deal. Separate Dev-mode log sounds interesting, but in my opinion it's not that important in the current state of the game. If similar issues arise a lot in the future, it might be a good idea to give it a thought.

We'll close this issue after you say that the stats are good.

By the way, kudos for the fast mitigation of the issue, update practically at the same day!

**Comment by Mikhael-Danilov** [comment] 2018-01-10 11:19
At least it intended. As those messages indicate errors in scripts, and modderes supposed to test their mods before distribution.

Thanks!

**Comment by Mikhael-Danilov** [comment] 2018-01-13 22:21
We can close it now

**Closed by Mikhael-Danilov** 2018-01-13 22:21 UTC
